### ISSUE TITLE
Can not find note

### ISSUE THREAD

**Issue by Pelid** [bordaigorl/sublime-evernote#101]
I have a note in russian language with title "У кого спросить совета". If I will try to search note with word "совет" in Evernote web client it works well. But I can not find anything by this word "совет" in sublime. Only "совета" works.

This bug is a show stopper. By this reason I can not find most of my notes.

PS. Thanks for your project. It is awesome!

**Comment by bordaigorl** [comment]
Hello, this is not due to the plugin but to Evernote's search language, fully documented [here](https://dev.evernote.com/doc/articles/search_grammar.php).
The solution is simple though: search for `совет*` and you will match `советa` and variants.

From the docs:

> Words or quoted phrases must exactly match a word or phrase in the note contents, note title, tag name, or recognition index. Words in the content of the note are split by whitespace or punctuation. Words may end in a wildcard to match the start of a word. Searches are not case sensitive. (A wildcard is only permitted at the end of the term, not at the beginning or middle for scalability reasons on the service.) Multiple whitespace and/or punctuation characters in the quoted phrase or the note will be compared as if they were a single space. The backslash escape character ('\') may be used to escape a quotation mark within a quoted phrase. E.g.:
> 
>  *  `potato`
>    - matches: "Sweet Potato Pie"
>    - does not match: "Mash four potatoes together"
>  *  `Ever*`
>    - matches: "Evernote Corporation"
>    - does not match: "forevernote" 
>  *  `"San Francisco"`
>    - matches: "The hills of San Francisco"
>    - does not match: "San Andreas fault near Francisco winery"
>  *  `-potato`
>    - matches: "Mash four potatoes together"
>    - does not match: "Sweet Potato Pie" 
>  *  `ham`
>       - matches: "green eggs&ham." 
>  *  `"eggs ham"`
>       - matches: "green eggs&ham."

**Comment by Pelid** [comment]
Wildcard works. Thanks.

**Comment by bordaigorl** [comment]
@Pelid if typing the wildcard annoys you, you can always pre-fill it in the prompt using

    { "command": "open_evernote_note", "args": {"by_searching": {"snippet": "$0*"}}}

and bind it to a key shortcut or substitute line 7 of `Evernote.sublime-commands` (copy to User folder and edit to prevent overwrites on update) with

    { "command": "open_evernote_note", "args": {"by_searching": {"snippet": "$0*"}}, "caption": "Evernote: Search Note" },
