### ISSUE TITLE
Can't type comma in tags array

### ISSUE THREAD

**Issue by prurph** [bordaigorl/sublime-evernote#104]
For some reason I'm unable to type a comma in between tags, as in `["my-tag", "my-other-tag"]`. I have to carriage return to make a new line, add the comma and then join the two lines (all the while still editing within the array braces).

Am I just doing something really stupid? I've reinstalled, restarted, created new notes, all to no avail.

**Comment by bordaigorl** [comment]
It may be a problem with the auto-completion.
The plugin installs a key bidingin for comma (when in the tags section of an Evernote note) to trigger the autocompletion for the tags. Maybe this is just very slow on your system?
Try setting `"evernote_autocomplete": false` in your user settings and see if it helps...

**Comment by prurph** [comment]
That avoids it, but I've also discovered my problem. I installed by cloning the repo instead of from package control so that I could add some extra pygments themes. This worked great but my package is at `/Packages/sublime-evernote/` whereas the macro for comma is looking at `res://Packages/Evernote/EvernoteAutoTagsQuoted.sublime-macro`. Changing the path fixes it.

Thanks for the awesome plugin!

**Comment by bordaigorl** [comment]
Ah, yes, that's something that breaks a few things here and there. If anybody knows a more general way to locate these files I'd be happy to implement it.
I should probably mention this in the README as well.
Thanks for reporting!
