### ISSUE TITLE
Add HTTPS support when insert image attachment.

### ISSUE THREAD

**Issue by Explorare** [bordaigorl/sublime-evernote#107]
The sublime crashed when I trid to insert a image with a https link.
Could you please fix it?
Thanks.

**Comment by bordaigorl** [comment]
HTTPS is already supported.
If it does not work for you it is maybe because ST3 for Linux does not support HTTPS by default.
You need to install Package Control 3 for a patch.

**Comment by bordaigorl** [comment]
@Explorare by closing the issue do you mean my suggestion solved it? (for future reference)

**Comment by Explorare** [comment]
It seems that the problem is more strange and complex but I can confirm the HTTPS support works well.

First I create a new note and a picture on two different site: 
    https://hime.io/images/2015/09/02/8863280320302178.jpg
    http://r5.loli.io/qAbER3.jpg

Then I insert the first pic into the note and succeed. And I can also see the pic correctly on sublime or EvernoteWeb. But I got error when I tried to insert the second link, here is error log:
>Evernote plugin error: HTTP Error 403: Forbidden
>	Last command: insert {'characters': 'T'}
>	(Evernote plugin v2.6.0, ST 3083, Python 3.3.3, windows x64)

I can visit this link correctly on my browser.How to fix this problem?

**Comment by Explorare** [comment]
I closed Sublime and reopen that note again and met another problem. When I use [Show Attachments] to preview the image and got this
![Image](https://hime.io/images/2015/09/02/8871817220721001.jpg)

Then I closed Sublime and open that note again and preview worked again this time.
![Image](https://hime.io/images/2015/09/02/8872009711448041.jpg)

What caused this problem?

**Comment by bordaigorl** [comment]
The 403 error seems a problem of communication with the server, nothing the plugin can handle.

The binary view of the file is caused by the filename: in the first case the extension is `.jpe` instead of `.jpg` or `.jpeg` (which are recognised by ST3 as images and displayed).
Again, this may have to do with the mimetypes sent by the server.

**Comment by Explorare** [comment]
Thanks for your help. I'll contact the webmaster to loli.io .
