### ISSUE TITLE
How to set up a short key for "insert_attachment_here"?

### ISSUE THREAD

**Issue by Explorare** [bordaigorl/sublime-evernote#109]
Here's what I set. But it won't work.

    { "keys": ["ctrl+e", "ctrl+i"], "command": "insert_attachment_here" },
    { "keys": ["ctrl+e", "ctrl+c"], "command": "view_note_in_evernote_client" },
    { "keys": ["ctrl+e", "ctrl+w"], "command": "view_note_in_webapp" }

Is something wrong?

**Comment by bordaigorl** [comment]
What's wrong is the names of the commands.
To know them you can have a look at `Packages/Evernote/Default.sublime-commands`.
There you can find for each entry in the quick panel which command is associated with it.
In your case you want

```json
{ "keys": ["ctrl+e", "ctrl+i"], "command": "evernote_insert_attachment" },
{ "keys": ["ctrl+e", "ctrl+c"], "command": "view_in_evernote_client" },
{ "keys": ["ctrl+e", "ctrl+w"], "command": "view_in_evernote_webapp" }
```

**Comment by Explorare** [comment]
It works. Thanks for your help.
