### ISSUE TITLE
Sync notebook list

### ISSUE THREAD

**Issue by theotheo** [bordaigorl/sublime-evernote#110]
Hi there! 
Thanks for the plugin, at first! 
So. I can't find how to sync notebook list. I've created new non-local notebook, but then I click "Open Evernote Note", I don't see this notebook listed there.

**Comment by bordaigorl** [comment]
I am not sure what you mean by "non-local notebook".
Anyway, the notebook list is cached for performance reasons.
It gets populated the first time you run "Open note" and the initial list is used until the next restart of ST.
One simple but manual way to refresh it is to call the `clear_evernote_cache` command. To do so you can open ST's console and type

     window.run_command("clear_evernote_cache")

after that calling "Open note" should reload the list.

I understand this may be confusing, I may consider adding a "refresh list" entry in the Notebook selection panel...

**Comment by theotheo** [comment]
It works. Thank you. I didn't guess to restart ST.

About "non-local notebook". I mean there are local notebooks and others -- i.e. non-local.  
![non-local notebook](https://cloud.githubusercontent.com/assets/1499744/9714437/9dcae22c-5560-11e5-89ab-6a272f1dad03.png)
