### ISSUE TITLE
Links based on link text aren't formatted

### ISSUE THREAD

**Issue by johnchristopherjones** [bordaigorl/sublime-evernote#111]
Link text Markdown links aren't converted into links when converted to Evernote.

Steps to reproduce:

1.  Create a note with the following body:
    > You're a new developer working with web technologies.  You're competent
    > in Javascript, though you might or might not be a “[ninja]”,
    > and you've been learning some [Angular], [Ember], or maybe [jQuery].
    > 
    > [angular]: https://angularjs.org
    > [ember]: http://emberjs.com
    > [ninja]: https://www.manning.com/books/secrets-of-the-javascript-ninja
    > [jQuery]: https://jquery.com

2.  Send/update note in Evernote and review

Expected result:
> The text "ninja", "Angular", "Ember", and "jQuery" are replaced with links.  The "footnote" links do not appear.

Actual Result:
> The aforementioned text appear literally as [ninja], [Angular], etc.  The "footnote" links at least do not appear.

**Comment by bordaigorl** [comment]
The syntax accepted by `markdown2` is `[ninja][]` (note the empty brackets).

Hence

```markdown
You're a new developer working with web technologies. You're competent
in Javascript, though you might or might not be a “[ninja][]”,
and you've been learning some [Angular][], [Ember][], or maybe [jQuery][].

[angular]: https://angularjs.org
[ember]: http://emberjs.com
[ninja]: https://www.manning.com/books/secrets-of-the-javascript-ninja
[jQuery]: https://jquery.com
```

should work as expected.

Again, this is due to the markdown conversion library that was choosen in the first release of the plugin.
As a long term plan, I would like to replace it with something more standard and less buggy but this takes time.
