### ISSUE TITLE
Tags/Notebook are not right in sublime if they where changed in the Evernote client

### ISSUE THREAD

**Issue by tommardh** [bordaigorl/sublime-evernote#112]
1. Save a note from Sublime
1. Update the tags in Evernote (e.g. add a new tag)
1. Open the note in Sublime again - The note is opened with the same tags as in step 1
1. If the note is saved from sublime the original tags are attached to the note in Evernote.

The same thing happens if you move the note to another notebook in Evernote. (Step 2)
When you open the note in Sublime again, the note is opened with the original notebook in the header.

I would really appreciate if this can be fixed, since I have started to use Sublime as my main editor for Evernote notes. This package is great! But sometimes I still do move or tag notes in the Evernote client.

Best Regards,
Tom Mårdh

**Comment by bordaigorl** [comment]
Good catch!!! I wonder how nobody noticed before.
The reason this happens is that the metadata is stored with the markdown sources.
This needs to be fixed for sure.
I'll think of a solution, if you have any suggestion that would be great.

Possible fixes:
 * strip the metadata from the embedded sources (drawback: custom metadata headers are lost)
 * parse the metadata as YAML (was in the todo list anyway) and update as necessary leaving the rest alone

**Comment by rdhyee** [comment]
About "I wonder how nobody noticed before": 

I had noticed something flaky but didn't try to nail the situation down precisely.  Thanks @tommardh for doing that work.

**Comment by tommardh** [comment]
Thanks for correcting this! Super!
