### ISSUE TITLE
How can I obtain a link to a note when I'm not in a tab of evernote

### ISSUE THREAD

**Issue by gisealine** [bordaigorl/sublime-evernote#118]
I want use the command **insert link to a note** when I haven't open a tab of evernote, because I only need to copy it to marxico, can anybody tell me how to do this, how to modify the **.sublime-commands** file. even better if you can tell how to copy the link of a note to clipboard directly.

**Comment by bordaigorl** [comment]
HOW DARE YOU ASK US HOW TO USE OUR PLUGIN TO SERVE MARXICO??? :rage3:
Just joking :stuck_out_tongue_winking_eye: 
I just pushed commit  e805205  that:
1. enables the command everywhere
2. adds the `template` and `to` options to the `insert_link_to_evernote_note` command. The default format is `"[{title}]({url})"` but you can also set it to `"{url}"` if you just need the url; `to` can accept `view` or `clipboard` as values. The former is the standard behaviour, the latter copies the result to clipboard.

To use this you need to use the devel branch as this change is not yet released.

Enjoy!

**Comment by gisealine** [comment]
I'm sorry about this, and much thanks for your improvement, I haven't known about it until yesterday, but now I found that I can't leave it!
