### ISSUE TITLE
Plugin error: Could not find style module 'github'

### ISSUE THREAD

**Issue by zhuzelong** [bordaigorl/sublime-evernote#119]
Mac OS X 10.11
Sublime Text 3

I wrote a markdown note and saved (updated) it but an error was raised

    Evernote plugin error: Could not find style module 'github'.
	Last command:  {}

Notes in plain text were fine but the note in markdown with code block failed. The strange part is that I have updated the note many times but it suddenly failed today without any settings changed.

**Comment by zhuzelong** [comment]
The issue is probably due to "code_highlight_style" where "github" would fail to update but any other styles would work.

**Comment by bordaigorl** [comment]
Thanks for reporting this. Could you please be a bit more specific on the version of ST/plugin you are using? Is it installed manually or via Package Control?
Could you also try to execute 

    sublime.find_resources("github.py")

In the ST console and report the result?
Pygments was updated to the new version at some point and there might be incompatibilities...

**Comment by zhuzelong** [comment]
I use ST3 the latest beta and the latest Evernote plugin via Package Control.

The result of the command is 

    ['Packages/Evernote/lib/pygments/styles/github.py', 'Packages/Markdown Preview/markdown/extensions/github.py']

**Comment by bordaigorl** [comment]
Thanks for the info. For the future: it is preferable to quote exact version numbers over "latest" since the latter changes over time while the version number could be useful for future reference.
Anyhow, have you tried to change `"code_highlight_style" ` to something like `"default"`? If that does not work there might be some incompatibilities with the latest ST beta's python and the version of pygments.

One thing you could do is calling

    import sys; sys.path

in the console to check if the `Evernote/lib` is correctly installed. In case it is you may even want to move it to the start or the end of the `sys.path` list to check if some other plugin is interfering.

The `github` style works fine on Linux ST 3086 with Evernote v2.7.

**Comment by zhuzelong** [comment]
Sorry about the version. I use ST3 build 3083 with Evernote plugin v2.7.0 installed via Package Control.

I referred to the wiki of plugin and tried all the "style". Every style worked fine except the "github".  I tried reinstalling the Evernote plugin but it did not help.

The only entry regarding `Evernote/lib` that I found in sys.path is 

    ~/Library/Application Support/Sublime Text 3/Installed Packages/Evernote.sublime-package/lib

**Comment by bordaigorl** [comment]
Could you show me the full output of `sys.path` please?
This could be a conflict with the Markdown Preview plugin. Do you have it installed?

**Comment by zhuzelong** [comment]
I have markdown preview installed. 

The full output of sys.path is 

    ['/Applications/Sublime Text.app/Contents/MacOS', '/Applications/Sublime Text.app/Contents/MacOS/python3.3.zip', '~/Library/Application Support/Sublime Text 3/Packages', '~/Library/Application Support/Sublime Text 3/Packages/pygments/all', '~/Library/Application Support/Sublime Text 3/Packages/bz2/st3_osx_x64', '~/Library/Application Support/Sublime Text 3/Packages/pyyaml/st3', '~/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package', '~/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package/emmet_completions', '~/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package/emmet', '~/Library/Application Support/Sublime Text 3/Installed Packages/Evernote.sublime-package/lib', '~/Library/Application Support/Sublime Text 3/Installed Packages/PyV8', '~/Library/Application Support/Sublime Text 3/Installed Packages/PyV8/osx-p3', '~/Library/Application Support/Sublime Text 3/Installed Packages/PyV8/pyv8-osx-p3', '~/Library/Application Support/Sublime Text 3/Packages/backrefs/st3']


The `import pygments.styles as s; s.STYLE_MAP['github']` did raise an KeyError. But the workaround did not work.

**Comment by zhuzelong** [comment]
I uninstalled Markdown Preview plugin then the "github" style worked again.

**Comment by bordaigorl** [comment]
Are you familiar enough with ST plugins? I could describe a temporary patch that you could try until I fix this for good.

**Comment by zhuzelong** [comment]
I am not so familiar with ST plugin. I will removed MD preview and wait for the fix. 

Thank you very much.

**Comment by dnutels** [comment]
Have the same issue. No change in plugins, so...

**Comment by bordaigorl** [comment]
I have a fix that seems to work but I haven't been able to properly test it.
Once I am more confident it works I'll release it.
 @dnutels would you volunteer as a tester?

**Comment by antiphasis** [comment]
i volunteer as tester, as i trapped into the very same situation. 
My Environment: Windows 10, ST 3 Dev Channel 3095,

**Comment by bordaigorl** [comment]
@antiphasis thanks a lot for offering your help!
I just pushed a new branch, `fix-mdprev-incompat` which should fix the problem.
After you replace your Evernote plugin directory with the one on that branch, make sure you restart ST (you may need to restart it twice) so that Package Control can pick up the changes and install the dependencies properly.
Let me know if it works!

**Comment by antiphasis** [comment]
@bordaigorl: First check done - all fine, no issues so far.

**Comment by bordaigorl** [comment]
Could you please check that:

 1. Markdown Preview works as expected
 2. Other values for the style setting work as expected
 3. If you create a new note in another Evernote client and then open it with the plugin everything works (this is related to another bug)

Thanks!

**Comment by antiphasis** [comment]
Ok, some more testing: 
  * Markdown Preview works as expected
  * as far as i can see, changes in the settings are reflected
  * created a note with Evernote Desktop: there's a problem with the presentation of unordered lists:

that's what it looks like: 
````markdown  
* unordered Level 1
  *     * unordered Level 2   
Shift - Enter for a new line
    * and one more
````

and that's what it should be
````markdown
  * unordered Level 1
    * unordered Level 2  
Shift - Enter for a new Line
    * and one more
```` 

Done a crosscheck with a note created a few month ago with sublime-evernote - same double star now.

**Comment by bordaigorl** [comment]
@antiphasis the nested list problem is probably unrelated to the changes in this branch.
It could be a known inconsistency in lists representation by the Evernote Desktop client (see #66).
Can you turn the `debug` setting on and see in the console what is the html of the note you are trying to open?

**Comment by antiphasis** [comment]
Created another short note in Evernote Desktop, opened it with debug enabled, see the xml below. It is from the debug output. From my point of view - an Evernote Editor problem. 

````xml
<en-note>
    <div>Testing the indentation of lists...</div>
    <div>
        <br/>
    </div>
    <ul>
        <li>A</li>
        <li>B</li>
        <li style="list-style: none; display: inline">
            <ul>
                <li>B.A</li>
                <li>B.B</li>
            </ul>
        </li>
        <li>C</li>
        <li>D</li>
    </ul>
    <div>
        <br/>
    </div>
    <div>
        <br/>
    </div>
    <ol>
        <li>A</li>
        <li>B
            <ol>
                <li>B.A</li>
                <li>B.B</li></ol>
        </li>
        <li>C</li>
        <li>D</li>
    </ol>
    <div>
        <br/>
    </div>
    <div>
        <br/>
    </div>
    <div>Done</div>
</en-note>
````

**Comment by fan123199** [comment]
Have the same issue. Also with Markdown Preview.

**Comment by leilater** [comment]
@bordaigorl Thank you so much! I had the same issue. I'm using the fix-mdprev-incompat now and it works well with Markdown Preview.

**Comment by UCASREN** [comment]
@bordaigorl @leilater How to replace Evernote plugin with fix-mdprev-incompat???? Very thx!

**Comment by bordaigorl** [comment]
@UCASREN select the branch from github and click on Download zip, then extract the contents to a folder named "Evernote" in your Sublime Text Packages folder (accessible from the "Preferences > Browse Packages" menu).
Then (re)start ST. Note that you need a recent version of Package Control for this to work and to complete the installation you may need a couple of restarts of ST.

**Comment by jangeroo** [comment]
For anyone else trying to replace their plugin with this branch, you may need to remove the original Evernote.sublime-package file from the Installed Packages folder. The branch version didn't work for me following the method above until I did that, but now it works perfectly :)
