### ISSUE TITLE
[v2.7.0] Table doesn't work correctly with a specific "body" property of inline_css.

### ISSUE THREAD

**Issue by gh594** [bordaigorl/sublime-evernote#128]
Updated to ver 2.7.0 and I add the body property, new style of CSS, into inline_css.
Everything works perfectly when I set it to "color:#333;" or "margin:40px;".
However,  when it was set to "color:#333; margin:40px;" and then I sent my note to Evernote, I got raw HTML (only tables) when I reopened the same note from Evernote.

**Comment by bordaigorl** [comment]
Found the bug, it's going to be fixed in the next release.
For a temporary patch, increase the number 150 at line 861 of `sublime_evernote.py`.
Thanks for reporting this!

**Comment by gh594** [comment]
Got that. It works well by increasing the number 150.
Thanks for replying!
