### ISSUE TITLE
Tab functionality for creating a new note, like snippets?

### ISSUE THREAD

**Issue by mbigras** [bordaigorl/sublime-evernote#132]
Hello,
Thanks so much for such an awesome package! I'm wondering if it is possible to tab through the creation of a note like when you use snippets? It seems like this would be very useful. I've included a video to describe more clearly what I'm talking about, but basically the way a note is created now you have to manually navigate through the different notebook, title, and tags fields and finally into the body of the note, is it possible to tab through these as if it were a snippet?

Also if it's not possible within the Evernote package do you know how I could create a snippet that could navigate around the existing meta section without disrupting it? I haven't figured out a way to do that (also included in the video and bellow)

One area that I'm making more progress is to create a snippet that creates the meta content and then I can tab through it; however, then I have to use the command palette to change the syntax to Evernote Note and then again use the command palette so send it to Evernote (also below and in the video)

Please see the video for a more detailed description and my (as of now) not working snippet attempts. Thanks so much if you decide to check it out! :)

[video that describes this in more detail](http://cl.ly/1L2T2D2R0s2b)

Snippet that creates meta information for note:
```xml
<snippet>
    <content><![CDATA[
---
title: ${2:Title}
notebook: ${1:Notebook}
tags: ${3}
---
${4}
]]></content>
    <!-- Optional: Set a tabTrigger to define how to trigger the snippet -->
    <tabTrigger>note</tabTrigger>
    <!-- Optional: Set a scope to limit where the snippet will trigger -->
    <!-- <scope>source.python</scope> -->
</snippet>
```
Snippet that fails to navigate through the existing meta section:
```xml
<snippet>
    <content><![CDATA[
      ${2:title}
${1:notebook}
     ${3:tag name}
${4:content}
]]></content>
    <!-- Optional: Set a tabTrigger to define how to trigger the snippet -->
    <tabTrigger>fill</tabTrigger>
    <!-- Optional: Set a scope to limit where the snippet will trigger -->
    <!-- <scope>source.python</scope> -->
</snippet>
```

**Comment by bordaigorl** [comment]
Hi, actually this should already work out of the box.
If you select the command "Evernote: Create new note" from the command pallette, a new view is created, pre-populated with a snippet that does what you ask. It also triggers autocomplete which may be interfering with your keybindings, you can also turn that off using the `evernote_autocomplete` setting to `false` in the plugin's settings.
In any case the snippet can be inserted by issuing an `"insert_snippet"` command with `"args": { "name": "Packages/Evernote/EvernoteMetadata.sublime-snippet"`.

I hope this helps. If this is not working on your system, check that the plugin is installed in a directory that is named "Evernote". If it's still not working let me know.

**Comment by mbigras** [comment]
Oh man! Haha I never tried tab again once I went down to tags! But it totally works, tabbing from notebook to tags to title and then to content, so perfect! Thanks for letting me know :)
