### ISSUE TITLE
Plain Text to Evernote Note to Synced with Evernote only works with Command Palette

### ISSUE THREAD

**Issue by mbigras** [bordaigorl/sublime-evernote#134]
Hey bordaigorl,

Thanks for getting back to me about the tabbing issue. I've come up with a use case that I think is really cool: Converting Plain Text documents to Evernote Notes using the meta information to more easily take advantage of snippets (even better would be to just be able to make snippets that interface with sublime-evernote but I'm not sure how to do that, is it possible?). Right now this is pretty tricky and I've only found one way to do it: manually with the command palette (please see my attached video). I think it might have to do with the GUID as described in #1. My understanding is that the GUID is the only way that our Evernote Note in Sublime knows how to talk to the Evernote Note in Evernote. I'm guessing a GUID gets assigned when a note is created or when the `SendToEvernoteCommand` command is run or maybe at other times too. I poked around in the python script and I don't know to much about python but I did see setting the note guid in there with `note.notebookGuid`  on line 580 in sublime_evernote.py; however, I didn't see any mention of the guid in `NewEvernoteNoteCommand` so I'm not sure exactly when or how you assign a guid to a note. But, do you think it would be possible to assign it earlier in the workflow from Plain Text -> Evernote? Or obviously if I'm way off base with the guid is there another way you think to go about creating snippets with sublime-evernote?

The video goes through the use case way more clearly. Thanks for such a rad package. Below is the video showing what I'm talking about as well as the snippets I used and the relevant section of my keybindings file. Looking forward to your thoughts :smiley:

[Link to use case video](http://cl.ly/1m1Z3k2f3r1I/Screen%20Recording%202016-04-23%20at%2001.59%20AM.mov)

simple note snippet:
```xml
<snippet>
    <content><![CDATA[
---
title: ${2:Title}
notebook: ${1:Notebook}
tags: ${3}
---
${4}
]]></content>
    <!-- Optional: Set a tabTrigger to define how to trigger the snippet -->
    <tabTrigger>note</tabTrigger>
    <!-- Optional: Set a scope to limit where the snippet will trigger -->
    <!-- <scope>source.python</scope> -->
</snippet>
```

image note snippet:
```xml
<snippet>
    <content><![CDATA[
---
title: ${2:Title}
notebook: ${1:Notebook} 
tags:
---
# ${3:Heading}
## ${4:Sub-heading}
![](${5:url})
${6:Explanation}
]]></content>
    <!-- Optional: Set a tabTrigger to define how to trigger the snippet -->
    <tabTrigger>image</tabTrigger>
    <!-- Optional: Set a scope to limit where the snippet will trigger -->
    <!-- <scope>source.python</scope> -->
</snippet>

```

quick note snippet:
```xml
<snippet>
    <content><![CDATA[
---
title: ${2:Title}
notebook: ${1:Notebook} 
tags:
---
# ${2:Heading}
## ${3:Sub-heading}
* ${4:Interesting bullet}
]]></content>
    <!-- Optional: Set a tabTrigger to define how to trigger the snippet -->
    <tabTrigger>quick</tabTrigger>
    <!-- Optional: Set a scope to limit where the snippet will trigger -->
    <!-- <scope>source.python</scope> -->
</snippet>

```

```javascript
.
.
.
// begin keymaps for sublime-evernote package
{ "keys": ["super+s"], "command": "save_evernote_note", "context": [{"key": "evernote_note"}, {"key": "evernote_has_guid"}] },
{ "keys": ["super+s"], "command": "send_to_evernote", "context": [{"key": "evernote_note"}, {"key": "evernote_has_guid", "operator": "equal", "operand": false}] },
{ "keys": ["super+e", "super+o"], "command": "open_evernote_note"},
{ "keys": ["super+e", "super+n"], "command": "new_evernote_note"},
{ "keys": ["super+e", "super+b"], "command": "create_notebook"},
// end keympas for sublime-evernote package
.
.
.
```

**Comment by bordaigorl** [comment]
The plugin already supports the workflow you outline.

## You do not need to set the syntax manually

There are multiple ways you can start a new note:
1. you can use the "Evernote: new empty note" command from the pallette, this sets everything up in the new view so that your keymaps should work as intended;
2. you can start from any view and select the "Evernote: Send to Evernote as a new note" command; this should also set the view up after uploading it to Evernote so that your keymap should work as intended.

## You do not need to use snippets

The plugin supports custom note templates out-of-the-box from version 2.7.0, see [this issue](https://github.com/bordaigorl/sublime-evernote/issues/74#issuecomment-137251574) for reference.
Basically the idea is that you can customise the default template that you get when using the "new empty note" command. If the template file name contains wildcards, you get a menu allowing you to select which of the matching templates you want to use. The templates can contain arbitrary text and are expected to use the snippet syntax.
You can also use this with keymaps, for example you may have

```json
\\ To have a choice of the template
{ "keys": ["super+e", "super+n"], "command": "new_evernote_note", "args": {"template": "Evernote *.md"}},
\\ To immediately start a new "quick note"
{ "keys": ["super+e", "super+q"], "command": "new_evernote_note", "args": {"template": "Evernote Quick Note.md"}},
```

Hope this helps.
- - -
Just for reference, here are my keybindings for the plugin:

```json
 // EVERNOTE
 { "keys": ["ctrl+e"], "command": "show_overlay", "args": {"overlay": "command_palette", "text": "Evernote: "} },
 { "keys": ["super+s"], "command": "save_evernote_note", "context": [{"key": "evernote_note"}, {"key": "evernote_has_guid"}] },
 { "keys": ["super+s"], "command": "send_to_evernote", "context": [{"key": "evernote_note"}, {"key": "evernote_has_guid", "operator": "equal", "operand": false}] },
 { "keys": ["f5"], "command": "view_in_evernote_client", "context": [{"key": "evernote_note"}, {"key": "evernote_has_guid"}] },
 { "keys": ["shift+f5"], "command": "view_in_evernote_webapp", "context": [{"key": "evernote_note"}, {"key": "evernote_has_guid"}] },
```

**Comment by mbigras** [comment]
Right on that this is supported out-of-the-box! I just haven't been able to get it working yet.

I've added the follow line to my keymap:
`{ "keys": ["super+e", "super+n"], "command": "new_evernote_note", "args": {"template": "Evernote *.md"}},`

I have the following `ImageNoteTemplate.md` file saved in a `Packages/User/evernote` directory:
```
---
title: ${2:Title}
notebook: ${1:Notebook} 
tags:
---
# ${3:Heading}
## ${4:Sub-heading}
![](${5:url})
${6:Explanation}
```
and I thought that should be enough to get it working but when I use `cmd + e + n` it doesn't show any templates, instead it creates a note as usual with drop down menus for notebook or tags but no templates.

so I tried putting `"default_template": "/Packages/User/evernote/ImageNoteTemplate.md"` in my `Evernote.sublime-settings` file but that also didn't work.

I'm not sure what I'm doing wrong but I suspect it's either:
1. My keybinding is wrong
2. (I think it's probably this) I'm setting up the template file wrong, but it seems to me that I'm using arbitrary text with snippet syntax, but maybe I'm missing some parts.
3. maybe the default_template needs to be set a different way.

Excited to figure this thing out!

**Comment by bordaigorl** [comment]
You are almost there: your paths are almost right.
I'll assume you want to put all your templates in `Packages/User/evernote` (note the absence of the initial `/` which would make the path absolute).
You can for example do:

    { "keys": ["super+e", "super+i"], "command": "new_evernote_note", "args": {"template": "Packages/User/evernote/ImageNoteTemplate.md"}},

to get the image note template when you press `super+ e + i`.
Or you could set

    "default_template": "Packages/User/evernote/*.md"

so that starting a new note would let you choose the template.

**Comment by mbigras** [comment]
Oh man! Thanks for spotting that mistake in my path. Now I'm really almost there. Key-mapping specifically to my custom templates works as expected! Woot woot!
![victory and celebration](http://cl.ly/3q2f1V1h3F1p/Slice%201.png)

**But** I'm still not getting this illusive drop down menu 😧 !! I don't know what I'm doing wrong. I've tried so many combinations. I was going to go through and paste all the different things I've tried in order but instead I'll just include them with different attempts commented out. I think the reason why I'm confused is because you're recommending that I set `"default_template": "Packages/User/evernote/*.md"` but I'm pretty sure that is supposed to go in my Evernote.sublime-settings file but then in an earlier post you recommended: 
```\\ To have a choice of the template
{ "keys": ["super+e", "super+n"], "command": "new_evernote_note", "args": {"template": "Evernote *.md"}},
```
 which I think goes in my Default.sublime-keymap file which I would then translate to
```\\ To have a choice of the template
{ "keys": ["super+e", "super+n"], "command": "new_evernote_note", "args": {"template": "Packages/User/evernote/*.md"}},
```
but I'm not sure and I'm feeling all mixed up. Here's my current setup below 

Default (OSX).sublime-keymap:
```
// open up my custom templates
{ "keys": ["super+e", "super+q"], "command": "new_evernote_note", "args": {"template": "Packages/User/evernote/QuickNoteTemplate.md"}},
{ "keys": ["super+e", "super+i"], "command": "new_evernote_note", "args": {"template": "Packages/User/evernote/ImageNoteTemplate.md"}},
//end custom templates
// To have a choice of the template
// { "keys": ["super+e", "super+n"], "command": "new_evernote_note", "args": {"template": "Evernote *.md"}},
{ "keys": ["super+e", "super+n"], "command": "new_evernote_note", "args": {"template": "Packages/User/evernote/*.md"}},
// { "keys": ["super+e", "super+n"], "command": "new_evernote_note"},
// end keymaps for sublime-evernote package
```
Evernote.sublime-settings:
```
{
	"extensions":[],
	"noteStoreUrl": " ;) ",
	"token": " ;) ",
    // "default_template": "Packages/User/evernote/*.md"
}
```

**Comment by bordaigorl** [comment]
Sorry, should have mentioned that the quick panel is only shown if there are multiple templates matching the pattern, otherwise the only match is used...does this help?

**Comment by mbigras** [comment]
No worries! Thanks for mentioning it now :wink:. It may help, I definitely think that's a very important detail. I think what it means is you have to develop your own naming convention for your templates, which is totally cool but I wish I could have read that somewhere in the documentation. It makes sense now because I've been using `*.md` to reference the two files `ImageNoteTemplate.md ` and `QuickNoteTemplate.md` but you've been using ` Evernote *.md` and I imagine it's because your templates have some naming convention like `Evernote template A.md` `Evernote template B.md`. It took me a little while to figure that out too because I'm not used to seeing spaces in file names (although more and more it seems like that's what sublime does, just think of the default keymap file). So it seems like the point isn't to use the `*` character to "tell sublime-evernote to list all occurances" it's more like to "create a situation where sublime-evernote can't choose which one to open" am I understanding this correctly?

So then I've renamed my files from `ImageNoteTemplate.md `-> `evernote_image_template.md` and `QuickNoteTemplate.md` -> `evernote_quick_bullet_template.md` but I'm still not exactly sure how to create the conflict. Do I do it by:

1. leaving my `Evernote.sublime-settings` file alone and putting `{ "keys": ["super+e", "super+n"], "command": "new_evernote_note", "args": {"template": "Packages/User/evernote/evernote_*.md"}}` in my  `Default (OSX).sublime-keymap ` file?
2. leaving my `Default (OSX).sublime-keymap` file alone and putting `"default_template": "Packages/User/evernote/evernote_*.md"` in my `Evernote.sublime-settings` file?
3. some combination of both?

I've tried 1 and 2 and various types of 3 but I still haven't been able to get it to work. Let me know :smiley:!

**Comment by bordaigorl** [comment]
I am sorry I made a mistake, actually what you need to provide is just the name of the file, not the path, in the pattern. This is due to a limitation of the ST3 API.
Technically, the filename *pattern* is fed to `sublime.find_resources` so you can put there whatever that function understands.

All in all this should work:

1. Name your templates using some convention (make your own). Here I assume you are naming them "Evernote NAMEOFTEMPLATE.md" and putting them in some subfolder of Packages. Another naming convention could use a custom extension like `.en-template`.
2. Set `default_template` (or the `template` argument of `new_evernote_note`) to a pattern matching the *names* of those files, for example `"Evernote *.md"`.

The name of the template can also be a path like `Packages/User/evernote/ImageNoteTemplate.md` but only when it is not a pattern, but a reference to a single file.

Hope this clarifies it, I am going to put some info in the wiki soon.

**Comment by mbigras** [comment]
:tada::tada::tada:
Right on bordaigorl thanks for sticking with me on this one. It's totally working and IMO an absolutely amazing feature! I went the route of passing my pattern to the `new_evernote_note` command. Below is my current `Evernote.sublime-settings` file (empty just to prove it can be :smiley:), my `Default (OSX).sublime-keymap` file to show how to use my chosen naming convention and how to pass arguments to `new_evernote_note`, and a screen-shot just because it also shows my file structure:

Evernote.sublime-settings:
```
{
	"extensions":[],
	"noteStoreUrl": " :) ",
	"token": " :) ",
}
```
Default (OSX).sublime-keymap:
```
// begin keymaps for sublime-evernote package
.
.
.
open up my custom templates
{ "keys": ["super+e", "super+q"], "command": "new_evernote_note", "args": {"template": "Packages/User/evernote/QuickNoteTemplate.md"}},
{ "keys": ["super+e", "super+i"], "command": "new_evernote_note", "args": {"template": "Packages/User/evernote/ImageNoteTemplate.md"}},
//end custom templates
// To have a choice of the template
{ "keys": ["super+e", "super+n"], "command": "new_evernote_note", "args": {"template": "evernote_*.md"}},
// To just create a new note
// { "keys": ["super+e", "super+n"], "command": "new_evernote_note"},
// end keymaps for sublime-evernote package
```
Screenshot:
![](http://cl.ly/2q232Q27441i/Screen%20Shot%202016-04-24%20at%205.01.50%20PM.png)
* A quick note about my naming convention that I think is cool: I put letters after the "evernote_" because the quick panel shows the templates in alphabetical order. So in my case I want to be able to access `evernote_A_quick_bullet_template.md` the fastest so I put the A there, that way when I use `cmd + e + n` and the quick panel drops down I can just hit enter and get right there. The rest of the letter really don't matter too much because you can just start searching and get where you want to go, but I do think it's cool to be able to choose which note will be selected if you just hit enter after toggling the quick panel and this seems to be working pretty well.

Thanks again bordaigorl, everything seems to be running smoothly...now if I could just figure out how to get Sublime to talk to Alfred .... man we'd be unstoppable :smirk: but that's really another story all together :persevere:

**Comment by bordaigorl** [comment]
Now the wiki has a page documenting this

https://github.com/bordaigorl/sublime-evernote/wiki/Creating-New-Notes

**Comment by mbigras** [comment]
![](http://cl.ly/0p1g3w2e1l07/feedback.png)
**note from attached screen shot**
My concern is that the Usage section does not describe that there are in fact also 2 different approaches that can be taken when choosing how to **reference** your templates, specifically you can put a full path or a pattern in `default_template` in your `Evernote.sublime-settings` file or you can put a full path or a pattern in your `Default (OSX).sublime-keymap` file. So in reality there are more than 2 ways to actually **set up** referencing for your custom templates (depending on what you want) because you can combine the 2 different approaches for **naming** and **referencing**. I think it may increase clarity if it gets stressed that:
1. You can choose how to name your templates and then you need to be aware of the difference between using those files individually (full path) or as part of a group (quick panel/filename pattern)
2. Once you decide how you want to name your templates its actually possible to achieve different effects by choosing where you want to reference those templates in `Evernote.sublime-settings` (with `default_template` or in `Default (OSX).sublime-keymap` (with keybindings)

What do you think?

**Comment by bordaigorl** [comment]
Feel free to add an explanation to the usage section, the wiki is freely editable :wink:

**Comment by mbigras** [comment]
Hey bordaigorl,

I didn't feel comfortable editing any of the parts that you wrote, but I did make a new page. I'm definitely excited to hear what you think and if there's any changes you'd like to see, or mistakes of course.
