### ISSUE TITLE
Feature request: drag & drop support

### ISSUE THREAD

**Issue by mrnobody0** [bordaigorl/sublime-evernote#135]
Hi,
I find this plugin **the most useful** way to use a Markdown with Evernote. Although, during a daily usage of the Evernote I find search capabilities of its native app more convenient than searching through this plugin (due to live search and results preview) - that's why I use both simultaneously.

Why am I saying this? It would be great to have a **drag & drop** support of a note from the Evernote native application to Sublime Text - to let user do an immediate editions.  
Without this functionality, I've to search a note two times: once in a native app - and then in the Sublime to open it.

What do you think?

// BTW: great plugin :)

Regards
Greg

**Comment by bordaigorl** [comment]
AFAIK there is no API in ST for drag&drop.
Simulating it with hacks does not seem to be a good idea.
One option would be to add a plugin to ST to enter an evernote link, parse the guid and open the note in ST as usual. Would that be usable?

**Comment by mrnobody0** [comment]
Hmm, it looks like you're right - I've done some research and didn't find anything...

But in my opinion, the solution proposed by you is still very usable and I would be really glad to see such functionality bound to some keyboard shortcut.

Greg

**Comment by bordaigorl** [comment]
Ok, I'll put it down for next release.
In the meantime, you can even cook this up yourself, by writing a plugin that uses `window.input_panel` to get the link from the user, you then extract the last chunk (say with `guid = link.split('/')[-1]`) of the link which is the guid of the note and then run

    view.run_command("open_evernote_note", {"note_guid": guid})
