### ISSUE TITLE
Error message when saving a note with a bold and italic next to each other

### ISSUE THREAD

**Issue by mrnobody0** [bordaigorl/sublime-evernote#138]
Hi,
I think I've found a small bug yesterday. My note contained following snippet:

```
**bold***italic*
```

And I was unable to save my note due to the following error message: 

```
Evernote complained:

The contents of the note are not valid.
The element type "em" must be terminated by the
matching end-tag "</em>".
```
Workaround: It is enough to add a single space between words, for example:

```
**bold** *italic*
```

Not a big deal, but wanted to let you know :)
Regards

-------
Screenshot below:

![screenshot from 2016-06-11 10-18-29](https://cloud.githubusercontent.com/assets/617283/15984152/32b93876-2fc1-11e6-8ecd-61d9e1babb30.png)

**Comment by bordaigorl** [comment]
Hi, thanks for the feedback.
This is one of the many quirks of the horrible markdown conversion library the plugin uses.
A migration to a better converter is planned but will take some time.
Any help in migrating to a saner converter is much appreciated.
