### ISSUE TITLE
Is it possible to add the notebook name to the sublime tab name?

### ISSUE THREAD

**Issue by devxplorer** [bordaigorl/sublime-evernote#153]
I call notes by date, it would be handy to see notebook name in the tab name, for example

Tab 1 name: diary 201016
Tab 2 name: work 201016

Is it possible?

**Comment by bordaigorl** [comment]
It's not currently possible but it would be a nice feature.
I'll put this down as todo for next release, thanks for the feedback!

**Comment by lex4ndr** [comment]
Ok, thanks for the quick response
