### ISSUE TITLE
Invalid auth

### ISSUE THREAD

**Issue by spfan** [bordaigorl/sublime-evernote#158]
I had config this file : 
`
{
	"noteStoreUrl": "balabala",
	"token": "S=balbala"
}
`

when execute ` Open Evernote Note ` , console show this.......

`
Evernote error: [Invalid auth]
	authenticationToken
	Last command:  {}
	BEFORE SUBMITTING AN ISSUE (https://github.com/bordaigorl/sublime-evernote/issues):
	  1. Enable the `debug` setting in your Evernote.sublime-settings file and try again. If the problem persists take a note of the output in the console.
	     Make sure you delete personal information (e.g. Developer Token) from the output before posting it in an issue.
	  2. Check the wiki at https://github.com/bordaigorl/sublime-evernote/wiki
	  3. Search for similar issues at https://github.com/bordaigorl/sublime-evernote/issues?q=is%3Aissue
	(Evernote plugin v2.7.2, ST 3126, Python 3.3.6, osx x64, debug)
error: Evernote cannot perform the requested action:
Authorisation error, consider re-configuring the plugin
Evernote: EDAMSystemException(errorCode=8, message='authenticationToken', rateLimitDuration=None)
`

**Comment by bordaigorl** [comment]
It could be a misconfiguration or an expired token.
Did the plugin ever work with that configuration?

Try selecting `Evernote Settings: Reconfigure Authorisation` from the command palette,
a webpage should open guiding you through the steps to get/renew your token.
Copy the token back to ST through the input panel and it should work.

**Comment by bordaigorl** [comment]
@spfan any luck with this one?

**Comment by spfan** [comment]
That didn't work:(
And when I tried to save `Evernote.sublime-settings`(settings-default),Sublime alert 
`Unable to save ~/Library/Application Support/Sublime Text 3/Packages/Evernote/Evernote.sublime-settings
Error: No such file or directory`
I found that `/Evernote` directory is not  in `/Packages` directory

**Comment by bordaigorl** [comment]
So maybe that's the problem. Have you installed the plugin via Package Control?
If not, you have to make sure that the plugin's directory is named "Evernote" and it is placed in ST's Packages directory. This is important for the plugin to work.

**Comment by spfan** [comment]
I had installed  the plugin via Package Control,unfortunately the "Evernote" directory did not exist.

**Comment by bordaigorl** [comment]
This is normal: Package Control installs plugins in a compressed form in a different directory.
You should aim at saving the setting file in your User folder.

**Comment by spfan** [comment]
I fixed this issue by reinstalling the plugin. 
Thank you very much!
