### ISSUE TITLE
Ctrl+e、Ctrl+o can work,but Ctrl+s.

### ISSUE THREAD

**Issue by a-lalala** [bordaigorl/sublime-evernote#168]
chang "*" to "\*",Ctrl+s ok!

**Comment by bordaigorl** [comment]
I am more than willing to help you, if you can express yourself more clearly 😉

**Comment by a-lalala** [comment]
think your reply!my meaning is the * type must escape \* ,else update will error

**Comment by bordaigorl** [comment]
I am sorry there might be a language barrier here, I have no idea what you are talking about.
If you are not a native English speaker, try to enclose your comment in your mother tongue, I might not be able to read it but other users may be able to translate it for me.

**Comment by a-lalala** [comment]
This problem has been solved!thank you very much!
I will type "* *",when update Evernote note,the plugin error and can't save this note.
now I type "* \*",update Evernote note ok!
