### ISSUE TITLE
how to set the keymap

### ISSUE THREAD

**Issue by yuedingwangji** [bordaigorl/sublime-evernote#170]
hello！ I have a quetion that how can I setting when I press "clrt+alt+o"  it will send this note to evernote as a new one in my evernote which note named myself_note .
the other quetion is as the last one ；
 how can I setting when I press "clrt+alt+e"  it will open my evernote which nameed myself_note 。

**Comment by bordaigorl** [comment]
For the second part have a look at the wiki:

https://github.com/bordaigorl/sublime-evernote/wiki/The-Open-Note-Command

For sending the note it depends on how you want this to work.
Do you want to create a new note in a given notebook? Append the contents to an existing note? Replace an existing note?
