### ISSUE TITLE
Authorisation error, consider re-configuring the plugin

### ISSUE THREAD

**Issue by spitz1jwq** [bordaigorl/sublime-evernote#175]
When I write the config like this 
`{
	"noteStoreUrl": "****",
	"token": "******"
}
`
it says that **Evernote cannot perform the requested action:
Authorisation error, consider re-configuring the plugin**

**Comment by bluebirch** [comment]
You must request a valid developer token from Evernote. RTFM.

**Comment by bordaigorl** [comment]
@spitz1jwq Please give us some context, the info you provide is not enough to understand and fix the issue.

Have you tried to use the "Reconfigure Authorisation" command and follow the instructions?
The wiki might also be helpful: https://github.com/bordaigorl/sublime-evernote/wiki/First-Use#important-authentication
