### ISSUE TITLE
blockquote display in Evernote Mac 6.11

### ISSUE THREAD

**Issue by 308820773** [bordaigorl/sublime-evernote#177]
![image](https://cloud.githubusercontent.com/assets/2957180/25213132/00d6f32e-25c1-11e7-90ef-e001be0726f8.png)
![image](https://cloud.githubusercontent.com/assets/2957180/25213143/11247256-25c1-11e7-8692-17ae118d8276.png)

**Comment by bluebirch** [comment]
Might be related to #176 and #174 since both concern Evernote for Mac 6.11.

**Comment by 308820773** [comment]
> Might be related to #176 and #174 since both concern Evernote for Mac 6.11.

Yes, You are right. The last version (7.2.11) is not have this problem.
