### ISSUE TITLE
Incorrect render of markdown to html

### ISSUE THREAD

**Issue by dbogdanov** [bordaigorl/sublime-evernote#183]
Code:
```
---
title: TEST (md)
tags: ["markdown"]
notebook: Tech
---

# Test header

Test text.

# Test header 2

Test text 2.
```

Result on Evernote:
![screen shot 2017-06-10 at 16 32 19](https://user-images.githubusercontent.com/409668/27003625-8237acea-4dfa-11e7-965c-b39eae99b127.png)

**Comment by bordaigorl** [comment]
I am not able to reproduce this...
