### ISSUE TITLE
unable to get token anymore...https://www.evernote.com/api/DeveloperToken.action

### ISSUE THREAD

**Issue by themikesam** [bordaigorl/sublime-evernote#201]
https://www.evernote.com/api/DeveloperToken.action

try to click and view?

**Comment by rdhyee** [comment]
I suggest [contacting Evernote support](https://www.evernote.com/SupportLogin.action) and filing a support ticket to get your account looked at.  I was not able to use a dev token either until Evernote reviewed my case.

**Comment by themikesam** [comment]
i was contacted, but i still haven't get any reply yet, therefore.
i'm here to suggest change the link from going to https://www.evernote.com/api/DevelopterToken.action to 'contacting Evernote Support' instead of going their website anymore when using reconfigure.

i have to spend some time on "Update: the creation of developer tokens is temporarily disabled."

Thanks for you reply.

**Comment by SugoiDev** [comment]
I just tested and I'm still able to generate tokens, but I've seen it happen before in #194
Is your account new?
Maybe they changed something, again.

**Comment by themikesam** [comment]
hi there,

can you provide the link?
i tried, it's still can't

​
Best Regards,

Mike Sam | 覃融亮
​National Chi Nan University | 國立暨南國際大學
Information Management | 資訊管理學系​

E-Mail: samson9565@gmail.com
​ | s104213069@mail1.ncnu.edu.tw​ <s104213069@mail1.ncnu.edu.tw%E2%80%8B>
Contact / WhatsApp : +60175654444 | +886(0)984335454
​Facebook Messenger:
​​
m.me/​themikesam
<https://mail.google.com/mail/u/0/http%E2%80%8Bs%E2%80%8B://m.me/%E2%80%8Bthemikesam>
LINE ID: mikesam06

2018-01-12 16:49 GMT+08:00 SugoiDev <notifications@github.com>:

**Comment by SugoiDev** [comment]
I just used the normal one: https://www.evernote.com/api/DeveloperToken.action
The last time this happened they eventually fixed the issue.

**Comment by themikesam** [comment]
Hi Sugoi Dev,

thanks for your help, but this is the result for me after clicking the link.



[image: 內置圖片 1]

​
Best Regards,

Mike Sam | 覃融亮
​National Chi Nan University | 國立暨南國際大學
Information Management | 資訊管理學系​

E-Mail: samson9565@gmail.com
​ | s104213069@mail1.ncnu.edu.tw​ <s104213069@mail1.ncnu.edu.tw%E2%80%8B>
Contact / WhatsApp : +60175654444 | +886(0)984335454
​Facebook Messenger:
​​
m.me/​themikesam
<https://mail.google.com/mail/u/0/http%E2%80%8Bs%E2%80%8B://m.me/%E2%80%8Bthemikesam>
LINE ID: mikesam06

2018-01-12 18:15 GMT+08:00 SugoiDev <notifications@github.com>:

**Comment by snario** [comment]
It's also unfortunate that in order to contact support in order to have them whitelist your account to get a developer token, you need a premium account.

**Comment by pplgin** [comment]
I wrote a website to get the token, you can contact me if you need it.

**Comment by themikesam** [comment]
what's the website?

**Comment by pplgin** [comment]
@themikesam https://pplgin.xyz/oauth

**Comment by bordaigorl** [comment]
@pplgin that's awesome! I haven't tried it but: would it be difficult for you to draft support for oauth directly in the plugin? Could you document the process you went through to get your third-party app approved etc?

**Comment by pplgin** [comment]
@bordaigorl `http://dev.evernote.com/doc/articles/authentication.php`. This is an authorized document, through the "oauth_consumer_key" to get the token. My website uses evernote-node-sdk, `https://github.com/pplgin/pplgin-evernote`, this is my website code.

```
API_CONSUMER_KEY(third-party app key) -> oauthToken -> accessToken(via oauthToken)
```

accessToken is what we need.

**Comment by rdhyee** [comment]
From Shane D (an Evernote employee) writing at [[faq] Developer Token Requests - Community Announcements - Evernote User Forum](https://discussion.evernote.com/topic/113349-developer-token-requests/):

> Hi All,
>
> We've been receiving some inquiries about how to acquire a Developer Token. (https://dev.evernote.com/doc/articles/dev_tokens.php)
>
> Previously, this was an automated process.
>
> Moving forward, developers will need to make a manual request in order to obtain a Developer Token.
>
> You can reach out directly to me via direct message, or you can make a request via [Support Ticket](https://help.evernote.com/hc/en-us/requests/new).
>
> Once enabled, you should be able to obtain a token [here](https://dev.evernote.com/doc/articles/dev_tokens.php).
>
> Hopefully this information provides some clarification on this process, and let me know if you have any questions!
