### ISSUE TITLE
Missing dependency pygments

### ISSUE THREAD

**Issue by ppoluha** [bordaigorl/sublime-evernote#202]
Failed to install on newly installed ST3 (latest build), getting message about missing dependency pygments. I've restarted ST3 several times. I managed to install manually but still getting messages about missing dependency. Then found pygments package at location https://github.com/packagecontrol/pygments/ and installed it in packages directory. After restart I get this:
Package Control: Installing 1 missing dependency
Package Control: The dependency 'pygments' is not available
Please advice!

**Comment by purgat0ri** [comment]
If you've downloaded the master branch of 'pygments' as a zip, you might sure that your packages directory *only* contains the pygments directory, not 'all' or 'pygments-master', etc. Also, after you install said package, make sure that you restart ST.

**Comment by ppoluha** [comment]
Now it looks like this. But the same error persists.
![pygments](https://user-images.githubusercontent.com/36794912/36639288-ca8c906a-1a09-11e8-9515-095bdc977040.jpg)
Shouldn't package control download and install dependencies? Something is broken.

**Comment by purgat0ri** [comment]
It should, yeah, but the above workaround fixed it for me (on Mac). I'm sorry it didn't work for you as well. :(
