### ISSUE TITLE
Unpack requires a bytes object of length 1

### ISSUE THREAD

**Issue by wennichnur** [bordaigorl/sublime-evernote#216]
Hi,

today I started getting an error. On the console I get this output:

	Evernote plugin error: unpack requires a bytes object of length 1
		Last command:  {}
		BEFORE SUBMITTING AN ISSUE (https://github.com/bordaigorl/sublime-evernote/issues):
		  1. Enable the `debug` setting in your Evernote.sublime-settings file and try again. If the problem persists take a note of the output in the console.
		     Make sure you delete personal information (e.g. Developer Token) from the output before posting it in an issue.
		  2. Check the wiki at https://github.com/bordaigorl/sublime-evernote/wiki
		  3. Search for similar issues at https://github.com/bordaigorl/sublime-evernote/issues?q=is%3Aissue
		(Evernote plugin v2.7.2, ST 3208, Python 3.3.6, windows x32)
	error: Evernote plugin error, please see the console for more details.
	Then contact developer at
	https://github.com/bordaigorl/sublime-evernote/issues

I have the problem on a Linux machine and a Windows machine (output above). I am not behind a proxy and the problem happens on different wi-fis & my mobile phone hotspot. I re-configured authorisation as suggested in #127 - no change. I un-installed and re-installed the plugin - no change.

I also tried these two commands; they both work:

	>>> import Evernote.lib.thrift as t; t.__file__
	'{removed}\\Sublime Text\\Data\\Installed Packages\\Evernote.sublime-package\\lib/thrift/__init__.py'
	>>> sublime.find_resources("Thrift.py")
	['Packages/Evernote/lib/thrift/Thrift.py']

Any ideas what I could do?

Thank you!

**Comment by alexcthompson** [comment]
I'm having the same problem.

**Comment by qunwang6** [comment]
me too

**Comment by bordaigorl** [comment]
I can confirm this is happening to me as well. I will try to investigate the issue in the weekend.
From a preliminary inspection, it seems that the Evernote server is not sending data and the protocol parser chokes on some handshaking.
The issue is not in how the plugin uses the Evernote SDK/API but in the communication between their servers and the SDK they provide (which is experimental for Python3 anyway).
If this is confirmed I am a bit worried that it would not be an easy thing to fix without their collaboration.

**Comment by bordaigorl** [comment]
Confirming my suspicion:
https://github.com/evernote/evernote-sdk-python3/issues/27
They have a workaround which I am going to push soon.
Let's hope Evernote get their act together and properly support Python3 with up-to-date SDK since Python2 is now deprecated anyway.

**Comment by bordaigorl** [comment]
Latest release fixes it for me.
Let me know if it worked.

**Comment by rdhyee** [comment]
@bordaigorl  https://github.com/bordaigorl/sublime-evernote/tree/2.7.3 fixed the problem for me -- I updated the package on SublimeText 3 and after restarting ST3, the problem went away.  **thank you**

**Comment by sangkong** [comment]
works!

**Comment by alexcthompson** [comment]
ty for the quick fix!
