### ISSUE TITLE
Unordered list markdown rendering

### ISSUE THREAD

**Issue by brynbellomy** [bordaigorl/sublime-evernote#32]
It'd be great if there were a way to specify an alternative to the built-in `*` character used when rendering UL elements as Markdown.  I have a fix for this, so this is more just a note to myself to create a pull request.

**Comment by tauren** [comment]
:+1: This would be nice to have. My work uses Atlassian Stash (like a private github service) which has really crappy rendering of readme.md files. If I use `-` for list items, rendering works nice, but using `*` sometimes attempts to italicize or bold content instead of indenting and bulleting.

**Comment by bordaigorl** [comment]
I added the settings `emphasis_mark`, `strong_mark` and `item_mark`.
By setting `"item_mark": "*"` you can change the default mark used when converting an Evernote note to markdown.
Be careful though: if you change these to unsupported markup (for instance `"emphasis_mark": "@"`) you will not be able to update the note correctly as the converter does not use these settings to find emphasis, strong and lists.

The changes are in the `devel` branch, soon to be released.
