### ISSUE TITLE
Enhancement: Support strikethrough

### ISSUE THREAD

**Issue by rahul-ramadas** [bordaigorl/sublime-evernote#38]
Please consider adding support for strikethrough, GFM-style. ~~Like this~~.

Currently, text that has been striked through in an Evernote client shows up like this:
```
<strike>Striked out text</strike>
```

**Comment by bordaigorl** [comment]
This is now implemented in the `devel` branch which will be soon released.
The syntax is the same as GitHub's: `~~text~~` becomes `<strike>text</strike>`.
(Note that GitHub uses `del` tags but Evernote does not understand them).
The web app uses `<span style="text-decoration: line-through;">` and that is supported too when converting to markdown.
