### ISSUE TITLE
Can't use plug-ins After upgrading to 3065

### ISSUE THREAD

**Issue by takizena** [bordaigorl/sublime-evernote#40]
Hello 

You have upgraded to Sublime text3 build 3065, was no longer available plug-ins. 

It was a phenomenon that occurred in OSX, but similar error has occurred after the upgrade even Windows. 

The following message was being displayed on the console.

```
Evernote plugin error: unpack requires a bytes object of length 1
error: Evernote plugin error, please contact developer at
https://github.com/bordaigorl/sublime-evernote/issues
```

**Comment by janhellmich** [comment]
I have had a very similar error message. It turned out that I entered the path to the Evernote file structure as my developer token, since the dev token wasn't shown on installation since it was used previously. I generated a new token and updated the plugin settings and it is working now.

**Comment by bordaigorl** [comment]
Hi @takizena @prokaktus @janhellmich if you are still looking for a solution t this it may be worth having a look at the discussion at #127 .
If any of you could try those instructions I would be very grateful.
