### ISSUE TITLE
Underlined formatting gets removed when importing/updating note

### ISSUE THREAD

**Issue by BuildingJarl** [bordaigorl/sublime-evernote#50]
Underline formatting is removed when importing/updating the note in sublime text.

Evernote then shows the following (_xxx_ is the text that was underlined):

```
_Hello_
_ 
_
_ 
_
_hello_
```

**Comment by bordaigorl** [comment]
@BuildingJarl At the end I went for using `==text==` to markup underlined text.
It works both ways now, from markdown to evernote and from evernote to markdown.
Check the `devel` branch or wait for next release to see the changes.
