### ISSUE TITLE
please support markdown table syntax

### ISSUE THREAD

**Issue by wizchentong** [bordaigorl/sublime-evernote#51]
I cannot create table .  - -!

**Comment by tauren** [comment]
It's great that tables can be rendered. But is there a reason to only support WikiTables and not GFM format?
https://help.github.com/articles/github-flavored-markdown/

It is inconvenient to use one format in github `readme.md` files and have to remember to use two pipes `||` in tables I want rendered in Evernote.

**Comment by bordaigorl** [comment]
This is scheduled to be included in next release (see #58).
I am quite busy at the moment so I cannot say when this will happen, but eventually the markdown parser will be updated and the new version supports GFM tables.

**Comment by bordaigorl** [comment]
This has been implemented in `devel` and is going to be in the next release.
