### ISSUE TITLE
Newline (carriage return) formatting not reflected in Evernote

### ISSUE THREAD

**Issue by tgig** [bordaigorl/sublime-evernote#67]
It seems that my newline formatting inside of Sublime Text is not getting uploaded to Evernote. I.e., newline space between paragraphs is removed.

This is what a note looks like in the text editor, with 2-3 carriage returns between each line: 

![00000837](https://cloud.githubusercontent.com/assets/1834003/5740838/0f0b1a10-9bbc-11e4-9fb2-6928b1a407e8.png)

When I create the note, it appears in my Evernote App for Mac as expected, but the space between the lines is gone. Looks like this: 

![00000838](https://cloud.githubusercontent.com/assets/1834003/5740864/3ae9d888-9bbc-11e4-86ef-3fa31e4d617b.png)

Is this a bug, or a settings issue?

Thanks for the ST plugin! This is such a cool one, and I appreciate the time you've spent to make it so good :)

**Comment by bordaigorl** [comment]
@tgig The conversion from plain text to rich text (HTML) is done by interpreting your plain text as Markdown. See the [wiki](https://github.com/bordaigorl/sublime-evernote/wiki/Supported-Markdown) for more details on how this is done and how to customise it.
Markdown does not translate new lines to new lines and that's why you see no extra new line in your note.

**Comment by tgig** [comment]
Thanks for the quick reply. Markdown is supposed to interpret 2 new lines as a paragraph tag. For example, here is a reply in github:

![2015-01-14_0750](https://cloud.githubusercontent.com/assets/1834003/5741786/59c73f88-9bc2-11e4-9e90-4f544e218e6b.png)

Here is the preview (with proper paragraphs, no matter how many carriage returns between the lines):

![2015-01-14_0750-b](https://cloud.githubusercontent.com/assets/1834003/5741795/69ed9268-9bc2-11e4-8c02-b6d8327fec76.png)

And here is the html code generated by the markdown (proper `<p>` tags)

![2015-01-14_0751-3](https://cloud.githubusercontent.com/assets/1834003/5741801/76dea0fc-9bc2-11e4-82cd-f8d112cce3ad.png)

So, perhaps the markdown-to-html engine you're currently using is just not correctly interpreting the new lines into `<p>` paragraph tags?

Also, and not sure if this is completely related, when I import an existing Evernote into sublime text, I have 5 lines between paragraphs and 8 lines between 3 EN carriage returns. Looks like this:

![2015-01-14_0757](https://cloud.githubusercontent.com/assets/1834003/5741867/f7321d10-9bc2-11e4-8d39-61e9efe257fb.png)

**Comment by bordaigorl** [comment]
To help me understand what's going on, could you please turn on the `debug` setting in your `Evernote.sublime-settings` file? This way you can see the converted/parsed HTML in the console...

**Comment by tgig** [comment]
The generated html actually looks pretty good. The `<p>` tags are getting generated just as I'd expect.

Here is a screen cap of a new note in ST:

![2015-01-14_0938](https://cloud.githubusercontent.com/assets/1834003/5743931/6b756a66-9bd1-11e4-9c02-380b73ef5458.png)

Here is a the code generated in the console:

```
>>> 
Evernote: Using cached notebooks list
Evernote: Using cached notebooks list
Evernote: <p>This is the third test in ST for evernote import.</p>

<p>This is a new paragraph, 2 carriage returns below the first line.</p>

<p>This is 3 returns below the line above.</p>

<p>This is 2 returns below.
This is just one return below.</p>

<p>This is a new paragraph, 2 returns below.</p>

Evernote: []
Evernote: Using cached notebooks list
Evernote: Test ST Note 3
Evernote: []
Evernote: 6ac96315-6c41-4a8e-8cbe-ceeac245b317
Evernote: <?xml version="1.0" encoding="UTF-8"?><!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd"><en-note>
<!-- Sublime:LS0tCnRpdGxlOiBUZXN0IFNUIE5vdGUgMwpub3RlYm9vazogdGdpZydzIG5vdGVib29rCnRhZ3M6Ci0tLQoKVGhpcyBpcyB0aGUgdGhpcmQgdGVzdCBpbiBTVCBmb3IgZXZlcm5vdGUgaW1wb3J0LgoKVGhpcyBpcyBhIG5ldyBwYXJhZ3JhcGgsIDIgY2FycmlhZ2UgcmV0dXJucyBiZWxvdyB0aGUgZmlyc3QgbGluZS4KCgpUaGlzIGlzIDMgcmV0dXJucyBiZWxvdyB0aGUgbGluZSBhYm92ZS4KClRoaXMgaXMgMiByZXR1cm5zIGJlbG93LgpUaGlzIGlzIGp1c3Qgb25lIHJldHVybiBiZWxvdy4KClRoaXMgaXMgYSBuZXcgcGFyYWdyYXBoLCAyIHJldHVybnMgYmVsb3cuCgoKCgo=-->
<p>This is the third test in ST for evernote import.</p>

<p>This is a new paragraph, 2 carriage returns below the first line.</p>

<p>This is 3 returns below the line above.</p>

<p>This is 2 returns below.
This is just one return below.</p>

<p>This is a new paragraph, 2 returns below.</p>
</en-note>
```

Here is a screen cap of the poorly formatted note in Evernote:

![2015-01-14_0939-2](https://cloud.githubusercontent.com/assets/1834003/5743943/77435ac4-9bd1-11e4-8db1-6797ada63b55.png)


**This makes it apparent that the new Evernote App for Mac is not formatting `<p>` tags properly...**

--------

And in reverse:

Here is a note created in Evernote:

![2015-01-14_0942](https://cloud.githubusercontent.com/assets/1834003/5743984/cbdc6918-9bd1-11e4-90fb-7e51df9bfa42.png)

Here is what it looks like when imported into Sublime Text (lots of extra space):

![2015-01-14_0944](https://cloud.githubusercontent.com/assets/1834003/5744000/eda09ab0-9bd1-11e4-8ba7-4a023fcadff6.png)

And here is what is generated in the console (**looks like the extra space is caused by wrapping `<br>`'s in `<div>`'s**):

```
Evernote: <?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd">
<en-note>
<div>This is a test note created in evernote.</div>
<div><br/></div>
<div>This is a new paragraph, 2 carriage returns below the above line.</div>
<div><br/></div>
<div><br/></div>
<div>This is a line that is 3 carriage returns below the above.</div>
<div><br/></div>
<div>This is 2 lines below.</div>
<div>This is 1 line below.</div>
<div><br/></div>
<div><br/></div>
</en-note>

Evernote: 1f9c78a7-cc8c-41b6-9694-8564e23b76b4
Evernote: Conversion ok
```

**Comment by bordaigorl** [comment]
Thanks a lot for the feedback.
So it would seem that these are discrepancies caused by how the client displays and converts content.
Making this look better would need ad hoc, per-client adjustments in the parsers of the plugin, something that I am not that incline in doing (it is very fragile, hard to maintain and I do not have access to all the clients).
Any suggestions on possible workarounds?

**Comment by tgig** [comment]
Hmmm... on the surface of things, it seems that Evernote handles `<br>` tags well, but not `<p>` tags.

I don't know how much (if any) flexibility you have with the markdown-to-html engine, but what would happen if each `\n` was a `<br>` in the generated code? (Instead of using the standard `<p>` tag)

Similarly, when pulling a note down, it seems that the combo of `<div>` and `<br>` causes extra spaces in the text editor - maybe the `<div>`'s could be eliminated, creating a standard language that all clients understand.

**Comment by tgig** [comment]
This is definitely _not_ a problem with the plugin. It's a display issue in the new Evernote for Mac app. Thanks for exploring it with me - I've submitted a ticket and a forum post to the folks at Evernote. Hopefully they get it fixed up on their end...

**Comment by agboh** [comment]
Hi tgig I was wondering if there had been any updates on the Evernote's end yet. I am getting the same problem one year after it was first brought up in this issue.

**Comment by tgig** [comment]
Hi @agboh - I never heard back from them that it was fixed... but they did fix it. When I look back on the same note that was causing problems before, it now displays correctly inside of Evernote. I am using Evernote for Mac 6.3.

**Comment by agboh** [comment]
Thank you for the quick reply. I am also using Evernote for Mac 6.3 but it still produces the extra space you mentioned above when notes are imported into Sublime Text.

<img width="809" alt="screen shot 2016-01-06 at 9 19 27 am" src="https://cloud.githubusercontent.com/assets/14964685/12132474/bb7df660-b456-11e5-8d8a-bacb51883de7.png">
<img width="1112" alt="screen shot 2016-01-06 at 9 20 05 am" src="https://cloud.githubusercontent.com/assets/14964685/12132475/be7b5a42-b456-11e5-94a1-4b1ea7b8c63f.png">

Just wondering if it is possible to convert `\n` into `<br>` instead of `<p>`, which would make the formatting much easier in this case.

**Comment by bgwwg** [comment]
I would suggest Sublime-evernote write <div> instead of <p> since Evernote never respects the <p> tag. Evernote replaces <p> with <div> if the paragraph is edited. 

version: Mac Evernote 6.6
