### ISSUE TITLE
Making changes to the default new note

### ISSUE THREAD

**Issue by Spardz** [bordaigorl/sublime-evernote#74]
Is there a way to edit the default contents that come up when you open a new empty note? I want to add some static information in all my notes for reference whenever I open a new note, like giving a default notebook name or default Heading structure.

**Comment by bordaigorl** [comment]
Currently not, the contents of the new note are hard-coded.
But it is a nice idea and easy to implement.
Added to the Todo list for next release!

Proposed fix:

 +  a `new_note_contents` setting that may contain a snippet, defaults to current snippet
 +  a `contents` argument for the `new_evernote_note` command (also a snippet)

**Comment by bordaigorl** [comment]
@Spardz as a temporary workaround you can overwrite the default contents by adding a simple plugin to your User folder as follows:

```py
import Evernote.sublime_evernote as evernote
evernote.META_SNIPPET = """\
---
title: $3
notebook: $1
tags: sublime, $2
---

Some boilerplate bla bla.
$0

"""
```
Change the contents to suit your needs (you can use the ST snippet syntax) and save this as a python file under `Packages/User` (you can find the directory using `Preferences > Browse Packages...`).

**Comment by Spardz** [comment]
@bordaigorl thank you very much. The workaround works perfectly.

**Comment by ptim** [comment]
:+1:  thanks!!

**Comment by bordaigorl** [comment]
@ptim @Spardz No need for the workaround anymore, the new version in `devel` now allows for more flexibility.
You can put a file in your `Packages/User` folder and then use the new setting `"default_template": "Packages/User/MyNoteTemplate.md` and that would be the initial contents of a new note.
You can use ST3's snippet syntax in the template.

Furthermore, you can set `default_template` to a file pattern as `Evernote Template*.md` and if more than one file matching the pattern is found in ST's resources (i.e. in `Packages` and subdirectories) then a quick panel is displayed from which you can pick.
This way you can have more than one template (e.g. one for each notebook).

Correspondingly, there are now two new parameters for the `new_evernote_note` command:
 * `contents` which can contain a snippet to be used as initial content
 * `template` (used if `contents` is not specified) that can override the `default_template` setting

In case no template is specified, the old snippet with just metadata is used.

**Comment by Spardz** [comment]
Awesome!!! Thanks again!!!
