### ISSUE TITLE
Code syntax in 'send to evernote' function

### ISSUE THREAD

**Issue by sztojka** [bordaigorl/sublime-evernote#78]
When I have a beautiful JS code syntax highlight in Sublime, is there a way to send it to Evernote while preserving the syntax highlight?

**Comment by bordaigorl** [comment]
The syntax highlighting is provided by the [`pygments`](pygments.org) library, not by ST.
`pygments` supports a number of different styles and you can control which one to use with the setting
`code_highlighting_style` documented [in the wiki](https://github.com/bordaigorl/sublime-evernote/wiki/Settings).

**Comment by sztojka** [comment]
Probably I am too noob for this, but I've set "code_highlighting_style":"github" in Evernote.sublime-settings, and after sending a js note to evernote, it still doesn't have any coloring, and the note loses some formatting as well (eg some indents).

I want the following: when I send a note from sublime to evernote, then I want to see the same code syntax formatting and coloring in evernote as I have in sublime.

**Comment by bordaigorl** [comment]
It looks like you are not using the right syntax for the contents of the note.
There are two ways to accomplish what you ask:

# 1 Using the Clip to Evernote command

1. Select some code in any view (with javascript highlighting turned on for the view)
2. open the command pallette (<kbd>ctrl+shift+p</kbd>)  and select "Clip to Evernote"
3. Follow the instructions

# 2 Using Markdown syntax

In your note use the "code block" syntax specifying `js` as language. For example writing in your note (in ST) the following

    ```js
    function unsubscribe ( listener ) {
        if ( arguments.length < 1 ){
          for ( var t in listeners ) {
            listeners[t] = [];
          }
          return this;
        }
        // etc
    }
    ```

and then sending it in Evernote would generate

```js
function unsubscribe ( listener ) {
    if ( arguments.length < 1 ){
      for ( var t in listeners ) {
        listeners[t] = [];
      }
      return this;
    }
    // etc
}
```

Please note that the highlighting will not necessarily match the one you see in ST.

**Comment by sztojka** [comment]
Awesome, thanks!
