### ISSUE TITLE
Show attachments not updating after deleting an attachment

### ISSUE THREAD

**Issue by kaspersoerensen** [bordaigorl/sublime-evernote#81]
After inserting an image to a note and then deleting it, the "Show Attachments" function does not seem to update properly (see image). The list shows 4 attachments, but there is only two in the note.

![skaermbillede 2015-04-14 kl 11 51 01](https://cloud.githubusercontent.com/assets/2018894/7134426/0a7e6c90-e29d-11e4-9547-0727b1de8c39.png)

**Comment by bordaigorl** [comment]
What do you mean by "deleting" the attachment?
Have you tried saving and then reopening the note?

**Comment by kaspersoerensen** [comment]
I mean that the attachment is no longer attached to the note. Save -> closing Sublime Text -> reopen the note does not work. It still shows all 4 attachments, even though there is only two.

**Comment by bordaigorl** [comment]
What I do not understand is how you are deleting the attachments. Via a client? The webapp? By just deleting the `enmedia` tag?

The Sublime plugin simply queries the Evernote server for detecting attachments so if it is showing 4 attachments that's the actual content of the note. Maybe they have been removed from the displayed content but are still stored...

**Comment by kaspersoerensen** [comment]
Ah okay. I deleted the ``<en-media>`` tag in Sublime - and the attachement disappeared from the desktop client, so I thought that the attachement was deleted.

**Comment by bordaigorl** [comment]
No, deleting the `<en-media>` is not sufficient: the attachments are stored in a field which is separate from the note's content and need to be managed separately.
Currently the plugin does not support deletion of attachments (nor of notes!) but there would be no difficulty in adding this in future releases.
Maybe I'll be able to release a new version in a month or so with this feature.

**Comment by kaspersoerensen** [comment]
Okay - that could be a nice feature :-)

**Comment by bordaigorl** [comment]
@kaspersoerensen This is now implemented in `devel`. If you could test it before I prepare the next release, I would really appreciate your help :wink:

**Comment by kaspersoerensen** [comment]
Cool. 
I will have a look at it by the end of this week.

**Comment by kaspersoerensen** [comment]
Yep - seems to be working! Nice job!
