### ISSUE TITLE
Save raw markdown

### ISSUE THREAD

**Issue by jincod** [bordaigorl/sublime-evernote#86]
Can i save raw markdown without convert to html?

**Comment by bordaigorl** [comment]
What exactly do you mean by "raw markdown"?
Do you mean you want to store a snippet of markdown code as a note?
Does [this](https://discussion.evernote.com/topic/80640-evernote-plugin-for-sublime-text-3-supports-markdown/?p=345952) help?

**Comment by jincod** [comment]
No. I want save: "# Test1" as text note: "# Test1".
![img](http://i.imgur.com/vxjLhBy.png)
(Test note created in web interface and opened in ST)

**Comment by bordaigorl** [comment]
You could wrap everything in a `<pre>` tag. Does that work for you?

**Comment by jincod** [comment]
Yes. Thx a lot
