### ISSUE TITLE
No authentication

### ISSUE THREAD

**Issue by jfoucry** [bordaigorl/sublime-evernote#89]
Sound strange, but authentication seems to not work :-(

The token request work perfectly and the Evernote.sublime-settings contain the correct informations:

{
    "noteStoreUrl": "https://www.evernote.com/shard/blahblah",
    "token": "blahblah",
    "debug": "yes"
} 

When I try to have the last note list, the console give me:

Evernote plugin error: unpack requires a bytes object of length 1
    Last command:  {}
    BEFORE SUBMITTING AN ISSUE (https://github.com/bordaigorl/sublime-evernote/issues):
      1. Enable the `debug` setting in your Evernote.sublime-settings file and try again. If the problem persists take a note of the output in the console.
         Make sure you delete personal information (e.g. Developer Token) from the output before posting it in an issue.
      2. Check the wiki at https://github.com/bordaigorl/sublime-evernote/wiki
      3. Search for similar issues at https://github.com/bordaigorl/sublime-evernote/issues?q=is%3Aissue
    (Evernote plugin v2.6.0, ST 3083, Python 3.3.3, osx x64, debug)
error: Evernote plugin error, please see the console for more details.
Then contact developer at
https://github.com/bordaigorl/sublime-evernote/issues
Evernote: unpack requires a bytes object of length 1

Nothing more (is debug mode enabled?).

Could it be a bad installation?

Thanks for your help

**Comment by bordaigorl** [comment]
Hi, thanks for the report.
This is a known unresolved issue with some configurations and I am still trying to figure out what's the cause (I cannot replicate it myself).
Related #59 

Are you behind a proxy?

**Comment by rhlobo** [comment]
Any solution for this? 

Evernote plugin v2.7.0, ST 3083, Python 3.3.3, windows x64, debug
Not using proxy

Error: `Evernote: unpack requires a bytes object of length 1`

**Comment by boweeb** [comment]
Still an issue here, too.  Both my mac at work and my archlinux at home.

OS X 10.11.3
Evernote plugin v2.7.0, ST 3083, Python 3.3.3, osx x64, debug

`Evernote: unpack requires a bytes object of length 1`

**Comment by iolaizola** [comment]
I get the same error as well.
Using Ubuntu 15.10 Sublime Build 3103

**Comment by bordaigorl** [comment]
Should be finally fixed, see #216
