### ISSUE TITLE
If I say Chinese

### ISSUE THREAD

**Issue by seekwe** [bordaigorl/sublime-evernote#98]
If I say Chinese:
不支持 #标题吗

**Comment by bordaigorl** [comment]
@seekwe I am sorry I cannot speak Chinese.
If you could try to explain the issue in English or with screenshots I could try to help, or maybe some other Chinese user can understand this and explain it?

**Comment by Strangehill** [comment]
I believe seekwe is saying that using # for headings doesn't work if you're using Chinese.

@seekwe 對嗎？is that right?

I have no problem with combining Chinese with headings, though.
我用#打標題沒有問題。

**Comment by bordaigorl** [comment]
Are you maybe using `#` without a space afterwards? That may be the reason why your headings are not recognised.

This works: 

    # 頭

This does not

    #頭

**Comment by 1ternal** [comment]
I'm pretty sure `# 标题` for heading works fine on mac.
